language: node_js
sudo: required
before_script:
  - npm install -g polymer-cli
  - polymer install --variants
node_js: '9'
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - polymer test
dist: trusty
cache:
  directories:
    - node_modules